version: '3.8'

services:
  coworkmy-frontend:
    image: nginx:alpine
    container_name: coworkmy-frontend
    volumes:
      - /opt/coworkmy/dist:/usr/share/nginx/html
      - /opt/coworkmy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3002:80"
    networks:
      - coworkmy-network

  coworkmy-backend:
    image: node:20-alpine
    container_name: coworkmy-backend
    working_dir: /app
    volumes:
      - /opt/coworkmy:/app
    ports:
      - "3003:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
    command: >
      sh -c "
        cd /app &&
        npm install --production --legacy-peer-deps &&
        npm start
      "
    networks:
      - coworkmy-network

networks:
  coworkmy-network:
    driver: bridge
