version: '3.8'

services:
  backend:
    image: node:20-alpine
    container_name: coworkmy-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      API_PORT: 5000
      DB_HOST: 147.93.58.155
      DB_PORT: 5432
      DB_NAME: coworkmy
      DB_USER: vpshostinger
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSL: true
      JWT_SECRET: ${JWT_SECRET}
      ALLOWED_ORIGINS: https://coworkmy.fr,https://www.coworkmy.fr
      FRONTEND_URL: https://coworkmy.fr
    volumes:
      - uploads_data:/app/uploads
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache git &&
        rm -rf /tmp/repo &&
        git clone https://github.com/hlafethi/coworkmy-clean.git /tmp/repo &&
        cp -r /tmp/repo/* /app/ &&
        npm install --omit=dev &&
        echo 'Starting API server...' &&
        node server.js
      "
    networks:
      - proxy
      - coworkmy-network

  frontend:
    image: node:20-alpine
    container_name: coworkmy-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    command: >
      sh -c "
        apk add --no-cache git nginx &&
        echo 'Cloning repository...' &&
        git clone https://github.com/hlafethi/coworkmy-clean.git /tmp/repo &&
        echo 'Installing dependencies...' &&
        cd /tmp/repo &&
        npm install &&
        echo 'Building frontend...' &&
        npm run build &&
        echo 'Copying built files...' &&
        mkdir -p /usr/share/nginx/html &&
        cp -r dist/* /usr/share/nginx/html/ &&
        cd / &&
        rm -rf /tmp/repo &&
        echo 'Creating nginx config with correct MIME types...' &&
        mkdir -p /etc/nginx/conf.d &&
        cat > /etc/nginx/conf.d/default.conf << 'EOF'
server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Correct MIME types for JavaScript modules
    location ~* \.js$ {
        add_header Content-Type application/javascript;
    }
    
    location ~* \.css$ {
        add_header Content-Type text/css;
    }

    # SPA routing: serve index.html for all routes
    location / {
        try_files $uri $uri/ /index.html;
    }
}
EOF
        echo 'Starting nginx...' &&
        nginx -g 'daemon off;'
      "
    networks:
      - proxy
      - coworkmy-network
    depends_on:
      - backend

volumes:
  uploads_data:

networks:
  proxy:
    external: true
  coworkmy-network:
    driver: bridge
