version: '3.8'

services:
  coworkmy-frontend:
    image: nginx:alpine
    container_name: coworkmy-frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    command: >
      sh -c "
        set -e &&
        apk add --no-cache git nodejs npm &&
        echo 'Cloning repository...' &&
        git clone https://github.com/hlafethi/coworkmy-clean.git /tmp/app &&
        cd /tmp/app &&
        echo 'Installing dependencies...' &&
        npm install &&
        echo 'Building application...' &&
        npm run build &&
        echo 'Copying built files...' &&
        mkdir -p /usr/share/nginx/html &&
        cp -r dist/* /usr/share/nginx/html/ &&
        cd / &&
        rm -rf /tmp/app &&
        echo 'Creating nginx config...' &&
        cat > /etc/nginx/conf.d/default.conf << 'EOF'
        server {
            listen 80;
            server_name _;
            root /usr/share/nginx/html;
            index index.html;

            location / {
                try_files $uri $uri/ /index.html;
            }
        }
        EOF
        echo 'Starting nginx...' &&
        nginx -g 'daemon off;'
      "
    networks:
      - coworkmy-network

  redis:
    image: redis:7-alpine
    container_name: coworkmy-redis
    restart: unless-stopped
    networks:
      - coworkmy-network
    ports:
      - "6381:6379"

networks:
  coworkmy-network:
    driver: bridge
