version: '3.8'

services:
  coworkmy-frontend:
    image: nginx:alpine
    container_name: coworkmy-frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    command: >
      sh -c "
        set -e &&
        apk add --no-cache git nodejs npm &&
        echo 'Cloning repository...' &&
        git clone https://github.com/hlafethi/coworkmy-clean.git /tmp/app &&
        cd /tmp/app &&
        echo 'Installing dependencies...' &&
        npm install &&
        echo 'Building application...' &&
        npm run build &&
        echo 'Copying built files...' &&
        mkdir -p /usr/share/nginx/html &&
        cp -r dist/* /usr/share/nginx/html/ &&
        cd / &&
        rm -rf /tmp/app &&
        echo 'Creating nginx config with API proxy...' &&
        cat > /etc/nginx/conf.d/default.conf << 'EOF'
        server {
            listen 80;
            server_name _;
            root /usr/share/nginx/html;
            index index.html;

            location /api/ {
                proxy_pass http://coworkmy-api:5000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location / {
                try_files $uri $uri/ /index.html;
            }
        }
        EOF
        echo 'Starting nginx...' &&
        nginx -g 'daemon off;'
      "
    networks:
      - coworkmy-network

  coworkmy-api:
    image: node:20-alpine
    container_name: coworkmy-api
    restart: unless-stopped
    working_dir: /app
    environment:
      - NODE_ENV=production
      - API_PORT=5000
      - DB_HOST=147.93.58.155
      - DB_PORT=5432
      - DB_NAME=coworkmy
      - DB_USER=vpshostinger
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSL=true
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=https://coworkmy.fr,https://www.coworkmy.fr
      - FRONTEND_URL=https://coworkmy.fr
    command: >
      sh -c "
        set -e &&
        apk add --no-cache git &&
        echo 'Cleaning /app directory...' &&
        rm -rf /app/* /app/.* 2>/dev/null || true &&
        echo 'Cloning repository for API...' &&
        git clone https://github.com/hlafethi/coworkmy-clean.git /tmp/api-app &&
        cp -r /tmp/api-app/* /app/ &&
        rm -rf /tmp/api-app &&
        echo 'Installing API dependencies...' &&
        npm install --omit=dev &&
        echo 'Creating minimal server to avoid path-to-regexp error...' &&
        cat > /app/minimal-server.js << 'EOF'
        import express from 'express';
        import cors from 'cors';
        import dotenv from 'dotenv';
        import { Pool } from 'pg';
        
        dotenv.config();
        
        const app = express();
        const PORT = process.env.API_PORT || 5000;
        
        // Middleware
        app.use(cors());
        app.use(express.json());
        
        // Database connection
        const pool = new Pool({
          host: process.env.DB_HOST,
          port: process.env.DB_PORT,
          database: process.env.DB_NAME,
          user: process.env.DB_USER,
          password: process.env.DB_PASSWORD,
          ssl: process.env.DB_SSL === 'true'
        });
        
        // Health check
        app.get('/api/health', (req, res) => {
          res.json({
            success: true,
            data: {
              status: 'OK',
              timestamp: new Date().toISOString(),
              version: '1.0.0'
            },
            error: null
          });
        });
        
        // Spaces endpoint
        app.get('/api/spaces', async (req, res) => {
          try {
            const result = await pool.query('SELECT * FROM spaces WHERE is_active = true');
            res.json({
              success: true,
              data: result.rows,
              error: null
            });
          } catch (error) {
            res.status(500).json({
              success: false,
              data: null,
              error: error.message
            });
          }
        });
        
        // Start server
        app.listen(PORT, () => {
          console.log('🚀 Minimal API CoworkMy démarrée sur le port', PORT);
        });
        EOF
        echo 'Starting minimal API...' &&
        node minimal-server.js
      "
    networks:
      - coworkmy-network

  redis:
    image: redis:7-alpine
    container_name: coworkmy-redis
    restart: unless-stopped
    networks:
      - coworkmy-network
    ports:
      - "6381:6379"

networks:
  coworkmy-network:
    driver: bridge
