version: '3.8'

services:
  # Application CoworkMy - Version simplifiée
  coworkmy-app:
    image: node:20-alpine
    container_name: coworkmy-app
    restart: unless-stopped
    working_dir: /app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=coworkmy
      - DB_USER=coworkmy_user
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSL=true
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=587
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - ALLOWED_ORIGINS=https://coworkmy.fr,https://www.coworkmy.fr,http://localhost:3000
      - FRONTEND_URL=https://coworkmy.fr
    command: >
      sh -c "
        apk add --no-cache git curl &&
        rm -rf /tmp/app &&
        git clone https://github.com/hlafethi/coworkmy-clean.git /tmp/app &&
        cp -r /tmp/app/* /app/ &&
        rm -rf /tmp/app &&
        npm install &&
        npm start
      "
    depends_on:
      - postgres
    networks:
      - coworkmy-network
    ports:
      - "3002:5000"
    volumes:
      - app_data:/app/node_modules

  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: coworkmy-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=coworkmy
      - POSTGRES_USER=coworkmy_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coworkmy-network
    ports:
      - "5433:5432"

volumes:
  postgres_data:
    driver: local
  app_data:
    driver: local

networks:
  coworkmy-network:
    driver: bridge
