version: '3.8'

services:
  coworkmy-frontend:
    image: nginx:alpine
    container_name: coworkmy-frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    command: >
      sh -c "
        set -e &&
        apk add --no-cache git &&
        echo 'Cloning repository...' &&
        git clone https://github.com/hlafethi/coworkmy-clean.git /tmp/app &&
        echo 'Copying built files...' &&
        mkdir -p /usr/share/nginx/html &&
        cp -r /tmp/app/dist/* /usr/share/nginx/html/ 2>/dev/null || echo 'No dist folder found' &&
        if [ ! -f /usr/share/nginx/html/index.html ]; then
          echo 'Creating placeholder index.html...' &&
          echo '<!DOCTYPE html><html><head><title>CoworkMy</title></head><body><h1>CoworkMy Application</h1><p>Frontend is being built...</p></body></html>' > /usr/share/nginx/html/index.html
        fi &&
        cd / &&
        rm -rf /tmp/app &&
        echo 'Creating nginx config...' &&
        echo 'server { listen 80; server_name _; root /usr/share/nginx/html; index index.html; location / { try_files $uri $uri/ /index.html; } }' > /etc/nginx/conf.d/default.conf &&
        echo 'Starting nginx...' &&
        nginx -g 'daemon off;'
      "
    networks:
      - coworkmy-network

  redis:
    image: redis:7-alpine
    container_name: coworkmy-redis
    restart: unless-stopped
    networks:
      - coworkmy-network
    ports:
      - "6381:6379"

networks:
  coworkmy-network:
    driver: bridge
