version: '3.8'

services:
  coworkmy-frontend:
    image: nginx:alpine
    container_name: coworkmy-frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    command: >
      sh -c "
        set -e &&
        apk add --no-cache git nodejs npm &&
        echo 'Cloning repository...' &&
        git clone https://github.com/hlafethi/coworkmy-clean.git /tmp/app &&
        cd /tmp/app &&
        echo 'Installing dependencies...' &&
        npm install &&
        echo 'Building application...' &&
        npm run build &&
        echo 'Copying built files...' &&
        mkdir -p /usr/share/nginx/html &&
        cp -r dist/* /usr/share/nginx/html/ &&
        cd / &&
        rm -rf /tmp/app &&
        echo 'Creating nginx config with API proxy...' &&
        cat > /etc/nginx/conf.d/default.conf << 'EOF'
        server {
            listen 80;
            server_name _;
            root /usr/share/nginx/html;
            index index.html;

            location /api/ {
                proxy_pass http://coworkmy-api:5000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location / {
                try_files $uri $uri/ /index.html;
            }
        }
        EOF
        echo 'Starting nginx...' &&
        nginx -g 'daemon off;'
      "
    networks:
      - coworkmy-network

  coworkmy-api:
    image: node:20-alpine
    container_name: coworkmy-api
    restart: unless-stopped
    working_dir: /app
    environment:
      - NODE_ENV=production
      - API_PORT=5000
      - DB_HOST=147.93.58.155
      - DB_PORT=5432
      - DB_NAME=coworkmy
      - DB_USER=vpshostinger
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSL=true
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=https://coworkmy.fr,https://www.coworkmy.fr
      - FRONTEND_URL=https://coworkmy.fr
    command: >
      sh -c "
        set -e &&
        apk add --no-cache git &&
        echo 'Cleaning /app directory...' &&
        rm -rf /app/* /app/.* 2>/dev/null || true &&
        echo 'Cloning repository for API...' &&
        git clone https://github.com/hlafethi/coworkmy-clean.git /tmp/api-app &&
        cp -r /tmp/api-app/* /app/ &&
        rm -rf /tmp/api-app &&
        echo 'Installing API dependencies...' &&
        npm install --omit=dev &&
        echo 'Starting API...' &&
        node server.js
      "
    networks:
      - coworkmy-network

  redis:
    image: redis:7-alpine
    container_name: coworkmy-redis
    restart: unless-stopped
    networks:
      - coworkmy-network
    ports:
      - "6381:6379"

networks:
  coworkmy-network:
    driver: bridge
