version: '3.8'

services:
  coworkmy-app:
    image: node:20-alpine
    container_name: coworkmy-app
    restart: unless-stopped
    working_dir: /app
    environment:
      - NODE_ENV=production
      - API_PORT=5000
      - DB_HOST=147.93.58.155
      - DB_PORT=5432
      - DB_NAME=coworkmy
      - DB_USER=vpshostinger
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSL=true
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=https://coworkmy.fr,https://www.coworkmy.fr
      - FRONTEND_URL=https://coworkmy.fr
    command: >
      sh -c "
        set -e &&
        apk add --no-cache git &&
        echo 'Cloning repository...' &&
        git clone https://github.com/hlafethi/coworkmy-clean.git /tmp/app &&
        cd /tmp/app &&
        git checkout master &&
        echo 'Copying files to /app...' &&
        cp -r . /app/ &&
        cd /app &&
        rm -rf /tmp/app &&
        echo 'Installing production dependencies...' &&
        npm ci --only=production &&
        echo 'Removing problematic server.js...' &&
        rm -f server.js &&
        echo 'Creating new clean server...' &&
        cat > server.js << 'EOF'
        const express = require('express');
        const cors = require('cors');
        const path = require('path');
        
        const app = express();
        
        app.use(cors());
        app.use(express.json());
        app.use(express.static('dist'));
        
        app.get('/api/health', (req, res) => {
          res.json({success: true, data: {status: 'OK', timestamp: new Date().toISOString()}});
        });
        
        app.get('*', (req, res) => {
          res.sendFile(path.join(__dirname, 'dist', 'index.html'));
        });
        
        const PORT = process.env.API_PORT || 5000;
        app.listen(PORT, () => {
          console.log('🚀 Server started on port', PORT);
        });
        EOF
        echo 'Starting application...' &&
        node server.js
      "
    networks:
      - coworkmy-network
    ports:
      - "3002:5000"

  redis:
    image: redis:7-alpine
    container_name: coworkmy-redis
    restart: unless-stopped
    networks:
      - coworkmy-network
    ports:
      - "6380:6379"

networks:
  coworkmy-network:
    driver: bridge
