version: '3.8'

services:
  coworkmy-app:
    build:
      context: https://github.com/hlafethi/coworkmy-clean.git#master
      dockerfile: Dockerfile.portainer
    container_name: coworkmy-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_PORT=5000
      - DB_HOST=147.93.58.155
      - DB_PORT=5432
      - DB_NAME=coworkmy
      - DB_USER=vpshostinger
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSL=true
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=587
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - ALLOWED_ORIGINS=https://coworkmy.fr,https://www.coworkmy.fr
      - FRONTEND_URL=https://coworkmy.fr
    networks:
      - coworkmy-network
    ports:
      - "3002:5000"

  redis:
    image: redis:7-alpine
    container_name: coworkmy-redis
    restart: unless-stopped
    networks:
      - coworkmy-network
    ports:
      - "6380:6379"

networks:
  coworkmy-network:
    driver: bridge
